apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: grafana-postgresql-datasource
    uid: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: karsa
    database: karsa
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    secureJsonData:
      password: karsa
