#!/bin/bash
# ============================================================================
# ASM 5-Hour Observation Report Generator
# ============================================================================
# Run after capture.sh completes to analyze collected data
# ============================================================================

set -euo pipefail

SESSION_DIR="$(cd "$(dirname "$0")" && pwd)"
SNAPSHOT_DIR="$SESSION_DIR/snapshots"
LOG_DIR="$SESSION_DIR/logs"
REPORT_FILE="$SESSION_DIR/OBSERVATION_REPORT.md"

echo "Generating 5-hour observation report..."

cat > "$REPORT_FILE" << 'HEADER'
# 🔬 ASM 5-Hour Observation Report

**Capture Period:** TBD (generated by report script)
**Focus:** Phase 1-3 features + critical bug fixes validation

---

## 📊 Executive Summary

| Category | Status | Details |
|----------|--------|---------|
| E2E Pipeline | TBD | Data → Decision → Risk → Execution flow |
| ELO Ratings | TBD | New feature population |
| Correlation Sizing | TBD | New feature population |
| Sector Scoring | TBD | New feature population |
| Volatility Surface | TBD | New feature population |
| Dynamic Gate | TBD | Threshold calibration working |
| Orphan Sync Fix | TBD | 5 USDT minimum enforced |
| SL Cap Fix | TBD | 5% max risk enforced |
| Breakeven Lock Fix | TBD | Scale-out → breakeven working |

---

## 📈 Feature Population Analysis

### ELO Ratings
```bash
grep -h "ELO" $SNAPSHOT_DIR/snapshot_*.txt | head -20
```

### Correlation Data
```bash
grep -h "CORRELATION" $SNAPSHOT_DIR/snapshot_*.txt | head -20
```

### Sector Scores
```bash
grep -h "SECTOR" $SNAPSHOT_DIR/snapshot_*.txt | head -20
```

### Volatility Surface
```bash
grep -h "VOL SURFACE" $SNAPSHOT_DIR/snapshot_*.txt | head -20
```

### Dynamic Gate Threshold
```bash
grep -h "GATE THRESHOLD" $SNAPSHOT_DIR/snapshot_*.txt | head -20
```

---

## 🔧 Critical Fixes Validation

### Orphan Sync (5 USDT Minimum)
```bash
grep -h "orphan" $LOG_DIR/*.log | grep -i "skip\|tiny\|5 USDT" | head -10
```

### Stop Loss Cap (5% Maximum)
```bash
grep -h "SL" $LOG_DIR/*.log | grep -i "cap\|MAX_RISK\|0.05" | head -10
```

### Breakeven Lock
```bash
grep -h "breakeven" $LOG_DIR/*.log | head -10
```

---

## 📊 Position Analysis

### Entry/Exit Distribution
```bash
grep -h "ENTRY\|EXIT" $LOG_DIR/*.log | wc -l
```

### Exit Reasons
```bash
grep -h "EXIT" $LOG_DIR/*.log | grep -oE "(stagnation|SL|TP|breakeven|trailing|regime)" | sort | uniq -c | sort -rn
```

### Position Duration
```bash
grep -h "EXIT" $LOG_DIR/*.log | head -20
```

---

## 💰 P&L Analysis

### Recent Trades
```bash
grep -A5 "RECENT TRADES" $SNAPSHOT_DIR/snapshot_*.txt | tail -30
```

### Wallet Balance Trend
```bash
grep -h "WALLET BALANCE" $SNAPSHOT_DIR/snapshot_*.txt
```

---

## ⚠️ Issues Found

### Errors
```bash
grep -h "ERROR" $LOG_DIR/*.log | sort | uniq -c | sort -rn | head -20
```

### Warnings
```bash
grep -h "WARN" $LOG_DIR/*.log | sort | uniq -c | sort -rn | head -20
```

---

## 🎯 Conclusions

### What Worked
- TBD after analysis

### What Needs Attention
- TBD after analysis

### Recommendations
- TBD after analysis

---

*Report generated: $(date '+%Y-%m-%d %H:%M:%S')*
*Snapshots analyzed: $(ls $SNAPSHOT_DIR/snapshot_*.txt 2>/dev/null | wc -l)*
*Log files analyzed: $(ls $LOG_DIR/*.log 2>/dev/null | wc -l)*
HEADER

# Actually analyze the data
echo "Analyzing captured data..."

# Count snapshots
SNAPSHOTS=$(ls "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | wc -l || echo "0")
echo "Found $SNAPSHOTS snapshots"

# Extract key metrics
echo -e "\n## 📊 Actual Metrics\n" >> "$REPORT_FILE"

# ELO ratings
ELO_KEYS=$(grep -h "karsa:elo:" "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | head -5 || echo "No ELO data found")
echo "### ELO Ratings Sample" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$ELO_KEYS" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Correlation
CORR_KEYS=$(grep -h "karsa:correlation:" "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | head -5 || echo "No correlation data found")
echo -e "\n### Correlation Data Sample" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$CORR_KEYS" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Vol surface
VOL_KEYS=$(grep -h "karsa:vol_surface:" "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | head -5 || echo "No vol surface data found")
echo -e "\n### Volatility Surface Sample" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$VOL_KEYS" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Gate threshold
GATE=$(grep -h "karsa:gate:dynamic_threshold" "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | head -3 || echo "No gate data found")
echo -e "\n### Dynamic Gate Threshold" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$GATE" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Position counts
echo -e "\n### Position Counts Over Time" >> "$REPORT_FILE"
grep -h "Live positions:" "$SNAPSHOT_DIR"/snapshot_*.txt 2>/dev/null | head -10 || echo "No position data" >> "$REPORT_FILE"

# Errors
ERRORS=$(grep -h "ERROR" "$LOG_DIR"/*.log 2>/dev/null | sort | uniq -c | sort -rn | head -10 || echo "No errors found")
echo -e "\n### Top Errors" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$ERRORS" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Exit reasons
echo -e "\n### Exit Reasons" >> "$REPORT_FILE"
grep -h "EXIT" "$LOG_DIR"/*.log 2>/dev/null | grep -oE "(stagnation|SL|TP|breakeven|trailing|regime)" | sort | uniq -c | sort -rn >> "$REPORT_FILE" 2>/dev/null || echo "No exit data" >> "$REPORT_FILE"

echo ""
echo "Report generated: $REPORT_FILE"
